# Generated by Django 4.0.3 on 2022-04-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
        migrations.CreateModel(
            name='VoteVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Вариант голосования',
                'verbose_name_plural': 'Варианты голосования',
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата голосования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавший пользователь')),
                ('vote_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votevariant', verbose_name='Вариант голосования')),
            ],
            options={
                'verbose_name': 'Голос пользователя',
                'verbose_name_plural': 'Голоса пользователей',
            },
        ),
    ]
