# Generated by Django 4.0.4 on 2022-04-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'ordering': ('-date_created',), 'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосования'},
        ),
    ]
