# Generated by Django 3.0.5 on 2020-12-17 17:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('publish_at', models.DateField()),
                ('finish_at', models.DateField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('surname', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=96)),
                ('email', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=8)),
                ('active', models.BooleanField()),
                ('posts', models.ManyToManyField(to='application.Post')),
            ],
        ),
    ]
