# Generated by Django 3.1.4 on 2020-12-19 22:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('author', models.IntegerField()),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('publish_at', models.DateTimeField()),
                ('finish_at', models.DateTimeField()),
                ('visible', models.BooleanField()),
            ],
        ),
    ]
