# Generated by Django 3.0.5 on 2020-12-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201222_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='name',
            new_name='title',
        ),
    ]
