# Generated by Django 3.0.5 on 2020-12-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201222_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Voting')),
            ],
        ),
    ]
