# Generated by Django 4.0.4 on 2022-04-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Требуется не более 20 знаков. Также можно использовать буквы, цифры и @/./+/-/_', max_length=20, unique=True, verbose_name='Логин'),
        ),
    ]
