# Generated by Django 4.0.3 on 2022-04-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservote',
            options={'verbose_name': 'Голос пользователя', 'verbose_name_plural': 'Голоса пользователей'},
        ),
        migrations.AlterModelOptions(
            name='votevariant',
            options={'verbose_name': 'Вариант голосования', 'verbose_name_plural': 'Варианты голосования'},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосования'},
        ),
        migrations.AddField(
            model_name='uservote',
            name='date_voted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата голосования'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавший пользователь'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='vote_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.votevariant', verbose_name='Вариант голосования'),
        ),
        migrations.AlterField(
            model_name='votevariant',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='votevariant',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.voting', verbose_name='Голосование'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Заголовок'),
        ),
    ]
